import React, { useEffect, useState } from 'react';
import { Steps } from 'intro.js-react';
import 'intro.js/introjs.css';

interface ProductTourProps {
  isEnabled: boolean;
  onExit: () => void;
  userType?: 'individual' | 'team' | 'enterprise';
}

const ProductTour: React.FC<ProductTourProps> = ({ isEnabled, onExit, userType = 'individual' }) => {
  const [currentStep, setCurrentStep] = useState(0);

  const baseSteps = [
    {
      element: '.dashboard-welcome',
      intro: `
        <div class="tour-step">
          <h3>🎉 Welcome to AIOS v2!</h3>
          <p>You're about to experience the power of AI-driven document processing. This quick tour will show you everything you need to know to get started.</p>
          <div class="tour-stats">
            <span>⏱️ 2 minutes</span>
            <span>🎯 5 key features</span>
            <span>🚀 Ready to go!</span>
          </div>
        </div>
      `,
      position: 'auto'
    },
    {
      element: '.upload-area',
      intro: `
        <div class="tour-step">
          <h3>📄 Upload Your First Document</h3>
          <p>Simply drag and drop any document here, or click to browse. AIOS v2 supports 50+ file formats including PDFs, Word docs, spreadsheets, and more.</p>
          <div class="tour-demo">
            <div class="demo-file">📄 sample-report.pdf</div>
            <div class="demo-arrow">→</div>
            <div class="demo-result">✨ Instant Analysis</div>
          </div>
        </div>
      `,
      position: 'bottom'
    },
    {
      element: '.ai-agents-panel',
      intro: `
        <div class="tour-step">
          <h3>🤖 Meet Your AI Agents</h3>
          <p>These specialized AI agents work together to process your documents. Each agent has unique skills - from data extraction to chart generation to summary writing.</p>
          <div class="tour-agents">
            <div class="agent-demo">📊 Data Agent</div>
            <div class="agent-demo">📈 Chart Agent</div>
            <div class="agent-demo">✍️ Summary Agent</div>
          </div>
        </div>
      `,
      position: 'right'
    },
    {
      element: '.processing-status',
      intro: `
        <div class="tour-step">
          <h3>⚡ Real-time Processing</h3>
          <p>Watch as your documents are processed in real-time. You'll see live updates, progress indicators, and results as they're generated by our AI agents.</p>
          <div class="tour-progress">
            <div class="progress-bar">
              <div class="progress-fill" style="width: 85%"></div>
            </div>
            <span>85% Complete - Generating summary...</span>
          </div>
        </div>
      `,
      position: 'top'
    },
    {
      element: '.results-dashboard',
      intro: `
        <div class="tour-step">
          <h3>📊 Your Results Dashboard</h3>
          <p>All processed documents and insights appear here. You can view summaries, download reports, share with team members, and export in multiple formats.</p>
          <div class="tour-features">
            <span>📥 Export PDF</span>
            <span>👥 Share Team</span>
            <span>📈 View Charts</span>
          </div>
        </div>
      `,
      position: 'top'
    }
  ];

  const teamSteps = [
    ...baseSteps,
    {
      element: '.collaboration-panel',
      intro: `
        <div class="tour-step">
          <h3>👥 Team Collaboration</h3>
          <p>As a team user, you can collaborate in real-time with your colleagues. Share workflows, assign tasks, and get notifications when documents are processed.</p>
          <div class="tour-collaboration">
            <div class="collab-feature">💬 Real-time Comments</div>
            <div class="collab-feature">🔔 Smart Notifications</div>
            <div class="collab-feature">📋 Task Assignment</div>
          </div>
        </div>
      `,
      position: 'right'
    }
  ];

  const enterpriseSteps = [
    ...teamSteps,
    {
      element: '.admin-panel',
      intro: `
        <div class="tour-step">
          <h3>🏢 Enterprise Controls</h3>
          <p>Access advanced admin features including user management, security settings, custom agent creation, and detailed analytics for your organization.</p>
          <div class="tour-enterprise">
            <div class="enterprise-feature">🔐 Security Center</div>
            <div class="enterprise-feature">📊 Analytics Dashboard</div>
            <div class="enterprise-feature">⚙️ Custom Agents</div>
          </div>
        </div>
      `,
      position: 'left'
    }
  ];

  const getStepsForUserType = () => {
    switch (userType) {
      case 'team':
        return teamSteps;
      case 'enterprise':
        return enterpriseSteps;
      default:
        return baseSteps;
    }
  };

  const finalStep = {
    element: '.get-started-button',
    intro: `
      <div class="tour-step tour-final">
        <h3>🚀 You're All Set!</h3>
        <p>You now know the basics of AIOS v2. Ready to process your first document? Click the "Upload Document" button and watch the magic happen!</p>
        <div class="tour-encouragement">
          <p><strong>💡 Pro Tip:</strong> Start with a PDF or Word document to see the best results.</p>
          <div class="tour-support">
            <span>❓ Need help? Check our <a href="/help" target="_blank">Help Center</a></span>
            <span>💬 Or use the chat widget in the bottom right</span>
          </div>
        </div>
      </div>
    `,
    position: 'top'
  };

  const allSteps = [...getStepsForUserType(), finalStep];

  // Debug logging
  useEffect(() => {
    console.log('🎬 ProductTour component rendered:', { isEnabled, userType, stepCount: allSteps.length });
    if (isEnabled) {
      console.log('✨ Tour should start now with', allSteps.length, 'steps');
      console.log('First step targets:', allSteps[0]?.element);
    }
  }, [isEnabled, userType, allSteps.length]);

  const showCompletionCelebration = () => {
    const celebration = document.createElement('div');
    celebration.className = 'tour-celebration';
    celebration.innerHTML = `
      <div class="celebration-content">
        <div class="celebration-emoji">🎉</div>
        <h2>Welcome aboard!</h2>
        <p>You're ready to transform your workflow with AIOS v2</p>
      </div>
    `;
    document.body.appendChild(celebration);

    setTimeout(() => {
      if (document.body.contains(celebration)) {
        document.body.removeChild(celebration);
      }
    }, 3000);
  };

  useEffect(() => {
    const style = document.createElement('style');
    style.id = 'aios-tour-styles';
    style.textContent = `
      /* Override default intro.js styles with AIOS v2 branding */
      .introjs-overlay {
        background: rgba(0, 0, 0, 0.8) !important;
        z-index: 999999 !important;
      }

      .introjs-tooltip {
        background: white !important;
        border-radius: 16px !important;
        box-shadow: 0 25px 50px rgba(0, 0, 0, 0.25) !important;
        border: 2px solid #667eea !important;
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif !important;
        max-width: 450px !important;
        min-width: 350px !important;
        z-index: 1000000 !important;
      }

      .introjs-tooltip .introjs-tooltiptext {
        padding: 24px !important;
        color: #374151 !important;
        line-height: 1.6 !important;
        font-size: 15px !important;
      }

      .introjs-tooltip .introjs-tooltipbuttons {
        padding: 0 24px 24px 24px !important;
        border-top: 1px solid #e5e7eb !important;
        margin-top: 16px !important;
        padding-top: 20px !important;
      }

      .tour-step h3 {
        margin: 0 0 16px 0 !important;
        color: #1f2937 !important;
        font-size: 20px !important;
        font-weight: 600 !important;
        display: flex !important;
        align-items: center !important;
        gap: 8px !important;
      }

      .tour-step p {
        margin: 0 0 20px 0 !important;
        color: #6b7280 !important;
        font-size: 14px !important;
        line-height: 1.6 !important;
      }

      .tour-stats, .tour-features, .tour-collaboration, .tour-enterprise {
        display: flex !important;
        gap: 12px !important;
        flex-wrap: wrap !important;
        margin-top: 16px !important;
      }

      .tour-stats span, .tour-features span, .tour-collaboration div, .tour-enterprise div {
        background: #f3f4f6 !important;
        padding: 8px 16px !important;
        border-radius: 20px !important;
        font-size: 12px !important;
        color: #4b5563 !important;
        font-weight: 500 !important;
        border: 1px solid #e5e7eb !important;
      }

      .tour-demo {
        display: flex !important;
        align-items: center !important;
        gap: 16px !important;
        margin-top: 16px !important;
        padding: 16px !important;
        background: #f8fafc !important;
        border-radius: 12px !important;
        border: 1px solid #e5e7eb !important;
      }

      .demo-file {
        background: #dbeafe !important;
        color: #1e40af !important;
        padding: 10px 16px !important;
        border-radius: 8px !important;
        font-size: 13px !important;
        font-weight: 500 !important;
        border: 1px solid #bfdbfe !important;
      }

      .demo-arrow {
        color: #10b981 !important;
        font-weight: bold !important;
        font-size: 18px !important;
      }

      .demo-result {
        background: #ecfdf5 !important;
        color: #059669 !important;
        padding: 10px 16px !important;
        border-radius: 8px !important;
        font-size: 13px !important;
        font-weight: 500 !important;
        border: 1px solid #a7f3d0 !important;
      }

      .tour-agents {
        display: flex !important;
        gap: 10px !important;
        margin-top: 16px !important;
        flex-wrap: wrap !important;
      }

      .agent-demo {
        background: #ede9fe !important;
        color: #7c3aed !important;
        padding: 8px 14px !important;
        border-radius: 16px !important;
        font-size: 12px !important;
        font-weight: 500 !important;
        border: 1px solid #d8b4fe !important;
      }

      .tour-progress {
        margin-top: 16px !important;
      }

      .progress-bar {
        width: 100% !important;
        height: 10px !important;
        background: #e5e7eb !important;
        border-radius: 6px !important;
        overflow: hidden !important;
        margin-bottom: 12px !important;
        border: 1px solid #d1d5db !important;
      }

      .progress-fill {
        height: 100% !important;
        background: linear-gradient(90deg, #10b981, #059669) !important;
        border-radius: 6px !important;
        transition: width 0.3s ease !important;
      }

      .tour-final {
        text-align: center !important;
      }

      .tour-encouragement {
        background: #f0f9ff !important;
        padding: 20px !important;
        border-radius: 12px !important;
        margin-top: 20px !important;
        border: 1px solid #bfdbfe !important;
      }

      .tour-encouragement p {
        margin: 0 0 16px 0 !important;
        color: #0369a1 !important;
        font-weight: 500 !important;
      }

      .tour-support {
        display: flex !important;
        flex-direction: column !important;
        gap: 10px !important;
      }

      .tour-support span {
        font-size: 12px !important;
        color: #6b7280 !important;
      }

      .tour-support a {
        color: #2563eb !important;
        text-decoration: none !important;
        font-weight: 500 !important;
      }

      .tour-support a:hover {
        text-decoration: underline !important;
      }

      .introjs-helperLayer {
        border: 3px solid #667eea !important;
        border-radius: 12px !important;
        box-shadow: 0 0 25px rgba(102, 126, 234, 0.4) !important;
        position: relative !important;
        z-index: 999998 !important;
      }

      .introjs-helperLayer::before {
        content: '' !important;
        position: absolute !important;
        inset: -6px !important;
        border-radius: 16px !important;
        background: linear-gradient(135deg, #667eea, #764ba2) !important;
        z-index: -1 !important;
        opacity: 0.2 !important;
      }

      .introjs-button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;
        border: none !important;
        color: white !important;
        padding: 12px 24px !important;
        border-radius: 8px !important;
        font-weight: 600 !important;
        cursor: pointer !important;
        transition: all 0.2s ease !important;
        font-size: 14px !important;
        text-transform: none !important;
        font-family: inherit !important;
      }

      .introjs-button:hover {
        transform: translateY(-2px) !important;
        box-shadow: 0 8px 20px rgba(102, 126, 234, 0.4) !important;
        background: linear-gradient(135deg, #5a67d8 0%, #667eea 100%) !important;
      }

      .introjs-skipbutton {
        background: transparent !important;
        color: #6b7280 !important;
        border: 2px solid #d1d5db !important;
        padding: 10px 20px !important;
        border-radius: 8px !important;
        font-weight: 500 !important;
        cursor: pointer !important;
        transition: all 0.2s ease !important;
        font-size: 14px !important;
        font-family: inherit !important;
      }

      .introjs-skipbutton:hover {
        background: #f9fafb !important;
        color: #374151 !important;
        border-color: #9ca3af !important;
        transform: translateY(-1px) !important;
      }

      .introjs-progressbar {
        background: #e5e7eb !important;
        height: 6px !important;
        border-radius: 3px !important;
        overflow: hidden !important;
      }

      .introjs-progressbar .introjs-progress {
        background: linear-gradient(90deg, #667eea, #764ba2) !important;
        height: 100% !important;
        border-radius: 3px !important;
        transition: width 0.3s ease !important;
      }

      .tour-celebration {
        position: fixed !important;
        top: 0 !important;
        left: 0 !important;
        right: 0 !important;
        bottom: 0 !important;
        background: rgba(0, 0, 0, 0.8) !important;
        display: flex !important;
        align-items: center !important;
        justify-content: center !important;
        z-index: 10000 !important;
        animation: fadeIn 0.3s ease !important;
      }

      .celebration-content {
        background: white !important;
        padding: 50px !important;
        border-radius: 20px !important;
        text-align: center !important;
        animation: slideInUp 0.5s ease !important;
        box-shadow: 0 30px 60px rgba(0, 0, 0, 0.3) !important;
        border: 2px solid #667eea !important;
      }

      .celebration-emoji {
        font-size: 60px !important;
        margin-bottom: 20px !important;
        animation: bounce 0.6s ease !important;
      }

      .celebration-content h2 {
        margin: 0 0 16px 0 !important;
        color: #1f2937 !important;
        font-size: 28px !important;
        font-weight: 700 !important;
      }

      .celebration-content p {
        margin: 0 !important;
        color: #6b7280 !important;
        font-size: 18px !important;
      }

      @keyframes fadeIn {
        from { opacity: 0 !important; }
        to { opacity: 1 !important; }
      }

      @keyframes slideInUp {
        from { 
          opacity: 0 !important;
          transform: translateY(50px) !important;
        }
        to { 
          opacity: 1 !important;
          transform: translateY(0) !important;
        }
      }

      @keyframes bounce {
        0%, 20%, 50%, 80%, 100% {
          transform: translateY(0) !important;
        }
        40% {
          transform: translateY(-20px) !important;
        }
        60% {
          transform: translateY(-10px) !important;
        }
      }
    `;
    document.head.appendChild(style);

    return () => {
      const existingStyle = document.getElementById('aios-tour-styles');
      if (existingStyle && document.head.contains(existingStyle)) {
        document.head.removeChild(existingStyle);
      }
    };
  }, []);

  return (
    <Steps
      enabled={isEnabled}
      steps={allSteps}
      initialStep={0}
      onExit={onExit}
      onComplete={() => {
        console.log('Product tour completed');
        onExit();
        showCompletionCelebration();
      }}
      onStepChange={(stepIndex: number) => {
        setCurrentStep(stepIndex);
        console.log(`Tour step ${stepIndex + 1} of ${allSteps.length}`);
      }}
      options={{
        tooltipClass: 'introjs-tooltip',
        highlightClass: 'introjs-helperLayer',
        exitOnEsc: true,
        exitOnOverlayClick: false,
        showStepNumbers: true,
        keyboardNavigation: true,
        showButtons: true,
        showBullets: false,
        showProgress: true,
        scrollToElement: true,
        overlayOpacity: 0.8,
        disableInteraction: false,
        nextLabel: 'Next →',
        prevLabel: '← Back',
        skipLabel: 'Skip Tour',
        doneLabel: 'Get Started! 🚀'
      }}
    />
  );
};

export default ProductTour; 